#producer #consumer
spring:
  rabbitmq:
#    addresses: 127.0.0.1:15672
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    listener:
      order:
        exchange:
          durable: true
          key: springboot.*
          name: order-exchange
          type: topic
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
