
spring:
#  (exclude = DataSourceAutoConfiguration.class)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sibyl?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sibyl?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
#      ds2:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/sibyl-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
    sharding:
      tables:
        warn_record:
          actual-data-nodes: ds1.warn_record_$->{1..2} #ds$->{1..2}.warn_record_$->{1..2}
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              waker:
                id: 1
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: warn_record_$->{id%2+1}
#            standard:
#              sharding-column: id
#              range-algorithm-class-name: com.sibyl.application.config.StandardTableStrategyRangeAlgorithm
#              precise-algorithm-class-name: com.sibyl.application.config.StandardTableStrategyPreciseAlgorithm
#          database-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: ds$->{id%2+1}
#            standard:
#              sharding-column: id
#              range-algorithm-class-name: com.sibyl.application.config.StandardDatabaseStrategyRangeAlgorithm
#              precise-algorithm-class-name: com.sibyl.application.config.StandardDatabaseStrategyPreciseAlgorithm
    props:
      sql:
        show: true
  aop:
    auto: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
