
spring:
  application:
    name:server: sibyl-activity
  port: 8080
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/sibyl-activity?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

project:
  manifest:
    file:
      path: classpath:/default-project.json